#!/bin/bash
set -ex
ETH='ens5'
WG='wg0'
WLAN=
HOST_PUB_IP='3.139.46.57/32'

[[ $UID != 0 ]] && exec sudo -E "$(readlink -f "$0")" "$@"

up() {
    killall wpa_supplicant dhcpcd || true
    ip netns add physical
    ip -n physical link add $WG type wireguard
    ip -n physical link set $WG netns 1
    wg setconf $WG /etc/wireguard/$WG.conf
    ip addr add $HOST_PUB_IP dev $WG
    ip link set $ETH down
    # ip link set $WLAN down
    ip link set $ETH netns physical
    iw phy phy0 set netns name physical
    ip netns exec physical dhcpcd -b $ETH
    # ip netns exec physical dhcpcd -b $WLAN
    # ip netns exec physical wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-${WLAN}.conf -i${WLAN}
    ip link set $WG up
    ip route add default dev $WG
}

down() {
    killall wpa_supplicant dhcpcd || true
    ip -n physical link set $ETH down
    # ip -n physical link set $WLAN down
    ip -n physical link set $ETH netns 1
    ip netns exec physical iw phy phy0 set netns 1
    ip link del $WG
    ip netns del physical
    dhcpcd -b $ETH
    # dhcpcd -b $WLAN
    # wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-${WLAN}.conf -i$WLAN
}

execi() {
    exec ip netns exec physical sudo -E -u \#${SUDO_UID:-$(id -u)} -g \#${SUDO_GID:-$(id -g)} -- "$@"
}

command="$1"
shift

case "$command" in
up) up "$@" ;;
down) down "$@" ;;
exec) execi "$@" ;;
*)
    echo "Usage: $0 up|down|exec" >&2
    exit 1
    ;;
esac
